name: emhrs-cron
description: EMHRS cron jobs
home: https://github.com/hmcts/emhrs-cron
apiVersion: v2
appVersion: "1.0"
version: 0.0.2
maintainers:
  - name: HMCTS Evidence Management team
dependencies:
  - name: job
    version: 2.2.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
